apiVersion: v1
name: mongodb-replicaset
version: 1.0
appVersion: 1.0
home: https://github.com/beergeek
description: Deploy MongoDB Enterprise Replica Set, securely.
maintainers:
  - name: beergeek
    email: brett.gray@mongodb.com